parameters:
    app.db_path: "%kernel.project_dir%/var/app.db"

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: "../src/"

    PDO:
        class: PDO
        arguments:
            - "sqlite:%app.db_path%"
        calls:
            - [
                  setAttribute,
                  [
                      !php/const PDO::ATTR_ERRMODE,
                      !php/const PDO::ERRMODE_EXCEPTION,
                  ],
              ]
